export type GeneralCurriculumTopic = {
  id: number;
  slug: string;
  title: string;
  explanation: string;
  example: string;
  exercise: string;
  tip: string;
};

export type GeneralCurriculumSection = {
  title: string;
  topics: GeneralCurriculumTopic[];
};

export const GENERAL_CURRICULUM: GeneralCurriculumSection[] = [
  {
    title: 'Basic 1 / Nivel Inicial',
    topics: [
      {
        id: 1,
        slug: 'general-zero-conditional',
        title: 'Zero Conditional',
        explanation: 'Se usa para expresar verdades universales, hechos cientificos y reglas logicas que siempre son ciertas. Ambas partes de la oracion van en presente simple: la condicion (if + subject + verb) y el resultado (subject + verb).',
        example: 'If you heat water to 100 degrees Celsius, it boils. / If it rains, the ground gets wet. / If you mix red and blue, you get purple.',
        exercise: 'Completa las oraciones con zero conditional: "If you _______ (not/sleep) enough, you feel tired." / "If you _______ (exercise) daily, your health _______  (improve)."',
        tip: 'Recuerda: ambas partes van en presente simple. No uses will ni would. Esta estructura es para hechos permanentes, no para situaciones futuras.',
      },
      {
        id: 2,
        slug: 'general-simple-present',
        title: 'Simple Present (Do/Does)',
        explanation: 'El presente simple describe rutinas, habitos y hechos permanentes. Para hacer preguntas y negaciones necesitas el auxiliar do (con I/you/we/they) o does (con he/she/it). Con does, el verbo principal regresa a su forma base sin -s.',
        example: 'Do you work on weekends? No, I do not work on weekends. / Does she speak English? Yes, she does. / They do not live here anymore.',
        exercise: 'Transforma estas oraciones: 1) "He plays soccer." (pregunta) 2) "I watch TV every night." (negacion) 3) "She works at a call center." (pregunta con does)',
        tip: 'Con does en preguntas, el verbo pierde la -s: Does he work? (no "Does he works?"). Con do not / does not la logica es la misma.',
      },
      {
        id: 3,
        slug: 'general-present-continuous',
        title: 'Present Continuous',
        explanation: 'Se usa para acciones que estan ocurriendo exactamente en este momento o en un periodo temporal cercano. Se forma con el verbo to be (am/is/are) mas el verbo principal terminado en -ing. Tambien se usa para planes futuros ya acordados.',
        example: 'I am studying English right now. / She is not working today, she is resting. / Are they coming to the meeting this afternoon? Yes, they are.',
        exercise: 'Escribe 3 oraciones sobre lo que estas haciendo ahora mismo y lo que NO estas haciendo: "I am _______ but I am not _______."',
        tip: 'Algunos verbos no se usan normalmente en continuo: know, like, love, hate, want, need. Di "I know" no "I am knowing".',
      },
      {
        id: 4,
        slug: 'general-can-cant',
        title: "Can / Can't",
        explanation: "Can expresa habilidad (saber hacer algo), posibilidad o permiso. Can't (cannot) es su negacion. Son iguales para todos los sujetos: no cambian con he/she/it. El verbo que sigue a can siempre va en forma base, nunca con to ni con -s.",
        example: "I can speak English and Spanish. / She can not drive yet, she is still learning. / Can you help me with this report? / He can solve complex problems very quickly.",
        exercise: "Escribe 2 cosas que puedes hacer bien y 2 que no puedes hacer todavia. Ejemplo: I can _______ but I can not _______ yet.",
        tip: "Despues de can/can't el verbo siempre va en forma base: I can speak (no I can to speak / no I can speaks). Para pedir permiso de forma mas cortés usa could.",
      },
      {
        id: 5,
        slug: 'general-prepositions-place',
        title: 'Prepositions of Place',
        explanation: 'In, on y at son las tres preposiciones de lugar mas importantes. In se usa para espacios cerrados o areas (in the room, in the city). On se usa para superficies (on the table, on the floor). At se usa para puntos especificos o lugares concretos (at the office, at home, at the bus stop).',
        example: 'My phone is on the desk. / The keys are in my bag. / I will meet you at the entrance. / She works at a call center in the city center.',
        exercise: 'Describe donde estan estos objetos usando in, on o at: "The laptop is _______ the desk." / "I am _______ home right now." / "The documents are _______ the folder."',
        tip: 'Truco facil: in = adentro de algo, on = encima de una superficie, at = en un punto exacto. At home, at work y at school son expresiones fijas muy comunes.',
      },
      {
        id: 6,
        slug: 'general-object-pronouns',
        title: 'Object Pronouns',
        explanation: 'Los pronombres de objeto reemplazan al sustantivo que recibe la accion del verbo. Son: me, you, him, her, it, us, them. Van despues del verbo o despues de una preposicion. Evitan repetir el nombre de la persona o cosa.',
        example: 'Can you call me later? / I saw her at the office yesterday. / Please send it to us by email. / I will help them with the report.',
        exercise: 'Sustituye el sustantivo por el pronombre correcto: "I need to call Maria." (I need to call _______.) / "Please help John and me." (Please help _______.) / "Send the file to the manager." (Send _______ to _______.',
        tip: 'Los pronombres de objeto nunca van solos como sujeto: di "She called me" no "Me called she". Despues de preposiciones siempre usa pronombres de objeto: for him, with us, to them.',
      },
      {
        id: 7,
        slug: 'general-countable-uncountable',
        title: 'Countable and Uncountable Nouns',
        explanation: 'Los sustantivos contables son cosas que puedes contar individualmente (apple, chair, idea). Los incontables son materias, liquidos o conceptos que no se pueden contar con numeros (water, money, information, advice). Los incontables no usan articulo a/an ni forma plural.',
        example: 'I need three chairs and some water. / Can you give me some information about the job? / There is a lot of traffic today. / I have two ideas for the project.',
        exercise: 'Clasifica estas palabras como contable (C) o incontable (U) y escribe una frase con cada una: rice / book / luggage / suggestion / hour / furniture.',
        tip: 'Nunca digas "an information" o "advices". Para los incontables usa: some information, a piece of advice, some luggage. Si necesitas contarlos usa una expresion: two pieces of advice.',
      },
      {
        id: 8,
        slug: 'general-quantifiers',
        title: 'Quantifiers',
        explanation: 'Los cuantificadores expresan cantidad sin dar un numero exacto. Some se usa en oraciones afirmativas. Any se usa en negativas y preguntas. Much se usa con incontables. Many se usa con contables. A lot of funciona con ambos. How much y how many son para preguntar cantidades.',
        example: 'There are many options available. / I do not have much time right now. / Do you have any questions? / I bought some snacks for the meeting. / We have a lot of work to do.',
        exercise: 'Elige el cuantificador correcto: "How _______ (much/many) people work in your company?" / "There is not _______ (much/many) coffee left." / "Do you have _______ (some/any) experience with CRM tools?"',
        tip: 'Regla basica: many = contables en plural, much = incontables. Pero a lot of funciona para ambos en afirmativas. En preguntas amables usa some: "Would you like some coffee?"',
      },
      {
        id: 9,
        slug: 'general-possessive-adjectives',
        title: 'Possessive Adjectives',
        explanation: 'Los adjetivos posesivos indican a quien pertenece algo: my, your, his, her, its, our, their. Siempre van antes del sustantivo y no cambian segun el numero o genero del objeto poseido. Se usan constantemente en conversaciones de trabajo y vida cotidiana.',
        example: 'This is my laptop. / Can I borrow your charger? / Her presentation was excellent. / We need to review our strategy. / Their office is on the third floor.',
        exercise: 'Completa con el adjetivo posesivo correcto: "The team finished _______ (they) project on time." / "Can you give me _______ (you) email address?" / "She updated _______ (she) resume last week."',
        tip: 'No confundas its (posesivo) con it\'s (contraccion de it is). "Its battery is dead" = la bateria esta muerta. "It\'s dead" = esta muerto/a.',
      },
      {
        id: 10,
        slug: 'general-verb-to-be',
        title: 'Verb To Be',
        explanation: 'To be (am/is/are) es el verbo mas fundamental del ingles. Se usa para describir identidad, profesion, estado, ubicacion y caracteristicas. No necesita auxiliar do/does para formar preguntas: se invierte el orden sujeto-verbo. Es el punto de partida de toda la gramatica inglesa.',
        example: 'I am a customer service agent. / She is very professional. / Are they available for the call? / We are not ready yet. / Is the system down? Yes, it is.',
        exercise: 'Forma 3 oraciones afirmativas, 2 negativas y 2 preguntas usando to be con diferentes sujetos: I, he, they, we, she.',
        tip: 'Para preguntar inviertes el orden: "She is ready" -> "Is she ready?" No uses do/does con to be. Las contracciones son muy comunes al hablar: I\'m, you\'re, he\'s, we\'re, they\'re.',
      },
    ],
  },
  {
    title: 'Basic 2',
    topics: [
      {
        id: 11,
        slug: 'general-simple-past',
        title: 'Simple Past (Did)',
        explanation: 'El simple past describe acciones completamente terminadas en el pasado. Los verbos regulares agregan -ed (worked, called, finished). Los irregulares tienen forma propia (went, said, had, got). Para preguntas y negaciones se usa el auxiliar did, y el verbo principal regresa a su forma base.',
        example: 'Did you call the client yesterday? Yes, I called him at 3 PM. / She did not finish the report on time. / We had a very productive meeting last week. / He solved the problem in 5 minutes.',
        exercise: 'Escribe estas oraciones en pasado: 1) "I speak with the manager." 2) "Do they send the email?" (pregunta en pasado) 3) "She does not arrive on time." (negacion en pasado)',
        tip: 'Con did en preguntas y negaciones el verbo vuelve a forma base: "Did you go?" (no "Did you went?"). Para irregulares memoriza los mas comunes: go/went, have/had, say/said, get/got, make/made.',
      },
      {
        id: 12,
        slug: 'general-past-continuous',
        title: 'Past Continuous',
        explanation: 'El past continuous (was/were + verb-ing) describe acciones que estaban en progreso en un momento especifico del pasado. Se usa frecuentemente junto con el simple past para indicar que una accion larga fue interrumpida por otra mas corta. Tambien sirve para dar contexto o ambiente a una historia.',
        example: 'I was working on the report when the client called. / What were you doing at 8 PM yesterday? / She was not listening during the meeting. / We were trying to solve the issue when the system crashed.',
        exercise: 'Une las dos acciones con when o while: 1) "I study / she arrives" 2) "He drives / it starts to rain" 3) "We discuss the project / the power goes out" Usa past continuous + simple past.',
        tip: 'Cuando dices "when" generalmente le sigue simple past (la interrupcion). Cuando dices "while" generalmente le sigue past continuous (la accion en progreso). "While I was working, he called."',
      },
      {
        id: 13,
        slug: 'general-be-going-to',
        title: 'Be Going To',
        explanation: 'Be going to (am/is/are going to + verbo base) expresa planes futuros ya decididos antes del momento de hablar, o predicciones basadas en evidencia visible. Es diferente de will porque implica que la decision ya se tomo o que hay una razon concreta para la prediccion.',
        example: 'I am going to apply for that job next week, I already prepared my resume. / Look at those dark clouds — it is going to rain. / We are going to launch the new product in March. / Is she going to attend the training?',
        exercise: 'Escribe 3 planes que tienes para la proxima semana usando be going to. Luego escribe 2 predicciones sobre el clima o una situacion que puedas ver ahora mismo.',
        tip: 'Si ya decidiste hacer algo = be going to. Si decides en el momento = will. "I am going to study tonight" (plan previo) vs "Ok, I will help you" (decision espontanea).',
      },
      {
        id: 14,
        slug: 'general-will-future',
        title: 'Will for Future',
        explanation: 'Will se usa para decisiones espontaneas tomadas en el momento de hablar, promesas, predicciones sin evidencia concreta y ofrecimientos. Es diferente de be going to. Will nunca cambia con el sujeto y siempre va seguido de verbo en forma base.',
        example: 'I will call you back in 5 minutes, I promise. / Will you help me with this? Of course, I will! / I think it will be a good year for the company. / I will have the coffee, please (decision en el momento).',
        exercise: 'Decide si usarias will o be going to: 1) You planned to study tonight. 2) A friend asks for help and you agree right now. 3) You see storm clouds and make a prediction. Explica tu razon.',
        tip: 'Truco: si tomaste la decision ANTES de hablar usa going to. Si la tomas AHORA mismo, usa will. "I will answer that" (lo decides en el momento). "I am going to answer that" (ya lo habias planeado).',
      },
      {
        id: 15,
        slug: 'general-comparative-adjectives',
        title: 'Comparative Adjectives',
        explanation: 'Los comparativos se usan para comparar dos personas, objetos o situaciones. Los adjetivos cortos (una silaba) agregan -er: fast/faster, tall/taller. Los largos (dos o mas silabas) usan more: more efficient, more professional. Siempre van seguidos de than para introducir el segundo elemento.',
        example: 'This process is faster than the previous one. / Working remotely is more flexible than going to the office. / The new software is better than the old one. / Is this plan cheaper than the other option?',
        exercise: 'Compara estos pares usando comparativos: 1) call center / email (fast) 2) morning shift / night shift (difficult) 3) your city / another city (big / small / expensive)',
        tip: 'Irregulares importantes: good -> better, bad -> worse, far -> farther/further. Con adjetivos de dos silabas terminados en -y cambia a -ier: happy -> happier, easy -> easier.',
      },
    ],
  },
  {
    title: 'Basic 3',
    topics: [
      {
        id: 16,
        slug: 'general-present-perfect',
        title: 'Present Perfect',
        explanation: 'El present perfect (have/has + participio pasado) conecta el pasado con el presente. Se usa para experiencias de vida (sin especificar cuando), acciones recientes con resultado presente, y situaciones que empezaron en el pasado y siguen ahora. Palabras clave: ever, never, just, already, yet, since, for.',
        example: 'I have worked in customer service for 3 years. / Have you ever handled an angry customer? / She has just finished the training. / I have not sent the report yet. / They have already solved the issue.',
        exercise: 'Escribe oraciones usando: 1) ever (pregunta sobre experiencia) 2) never (algo que nunca has hecho) 3) already (algo que acabas de terminar) 4) yet (algo que no has hecho todavia)',
        tip: 'Present perfect = conexion con el presente. Simple past = accion completamente en el pasado. "I lost my phone" (ya no importa cuando) vs "I have lost my phone" (todavia no lo encuentro, me afecta ahora).',
      },
      {
        id: 17,
        slug: 'general-superlative-adjectives',
        title: 'Superlative Adjectives',
        explanation: 'Los superlativos expresan el grado extremo de una cualidad dentro de un grupo de tres o mas. Los adjetivos cortos agregan -est: the fastest, the tallest. Los largos usan the most: the most important, the most reliable. Siempre van precedidos de the.',
        example: 'This is the most difficult case I have ever handled. / She is the best agent in the team. / What is the cheapest plan available? / Monday is the busiest day of the week for us.',
        exercise: 'Escribe superlatives para estas situaciones: 1) El proceso mas lento de tu trabajo 2) El cliente mas complicado que has tenido 3) La habilidad mas importante para tu trabajo',
        tip: 'Irregulares: good -> the best, bad -> the worst, far -> the farthest/furthest. Adjetivos con -y: easy -> the easiest, happy -> the happiest. Siempre necesitas "the" antes del superlativo.',
      },
      {
        id: 18,
        slug: 'general-adverbs-manner',
        title: 'Adverbs of Manner',
        explanation: 'Los adverbios de modo describen como se realiza una accion. La mayoria se forman agregando -ly al adjetivo: clear -> clearly, professional -> professionally, quick -> quickly. Van generalmente despues del verbo o al final de la oracion. Ayudan a sonar mas preciso y profesional.',
        example: 'She explained the issue clearly. / He handled the situation professionally. / Please speak slowly so I can understand. / I will send the report shortly. / The team worked efficiently under pressure.',
        exercise: 'Convierte estos adjetivos en adverbios y usaelos en una frase sobre tu trabajo: careful / confident / polite / effective / direct.',
        tip: 'Adjetivos terminados en -ic agregan -ally: basic -> basically, automatic -> automatically. Irregulares comunes: good -> well, fast -> fast (sin -ly), hard -> hard (sin -ly, "hardly" significa "casi no").',
      },
      {
        id: 19,
        slug: 'general-should-shouldnt',
        title: "Should / Shouldn't",
        explanation: 'Should expresa recomendacion, consejo o expectativa. Es mas suave que must (obligacion). Se usa para dar sugerencias profesionales, hablar de lo que es correcto hacer o describir expectativas. Should not (shouldn\'t) indica que algo no es recomendable. El verbo que sigue siempre va en forma base.',
        example: "You should document every call for quality purposes. / She shouldn't promise things she can't deliver. / Should I escalate this case or handle it myself? / Agents should always confirm the customer's name at the start.",
        exercise: "Da 3 consejos para alguien que empieza a trabajar en un call center usando should y shouldn't. Ejemplo: You should listen carefully before responding.",
        tip: 'Should es consejo, must es obligacion. "You should arrive on time" (te lo recomiendo) vs "You must arrive on time" (es obligatorio). Para preguntar consejo: "Should I call back or send an email?"',
      },
      {
        id: 20,
        slug: 'general-present-perfect-reinforcement',
        title: 'Present Perfect (Refuerzo)',
        explanation: 'Refuerzo del present perfect enfocado en already, yet, since y for. Already indica que algo paso antes de lo esperado (va en oraciones afirmativas). Yet indica que algo no ha pasado todavia (va en negativas y preguntas). Since se usa con un punto de inicio en el tiempo. For se usa con una duracion.',
        example: 'I have already sent the email, you should have it. / Have you finished the report yet? No, not yet. / She has been in this role since January. / We have been waiting for the response for two hours.',
        exercise: 'Escribe 4 oraciones sobre tu situacion laboral o de estudio: una con already, una con yet, una con since y una con for.',
        tip: 'Already generalmente va entre have/has y el participio: "I have already done it." Yet va al final: "I have not done it yet." Since + punto especifico: since 2020, since Monday. For + duracion: for 3 years, for a few minutes.',
      },
    ],
  },
  {
    title: 'Intermediate and Advanced',
    topics: [
      {
        id: 21,
        slug: 'general-first-conditional',
        title: 'First Conditional',
        explanation: 'El first conditional expresa situaciones reales y posibles en el futuro. La condicion usa presente simple (if + subject + verb) y el resultado usa will + verbo base. Se usa para hablar de consecuencias probables, advertencias, promesas y acuerdos profesionales.',
        example: 'If you practice every day, you will improve your English quickly. / If the client calls back, I will transfer the call to you. / Will you help me if I get stuck? / If we miss the deadline, the client will not be happy.',
        exercise: 'Completa con first conditional: 1) "If you _______ (study) tonight, you _______ (pass) the exam." 2) "If she _______ (not/call), we _______ (send) an email." 3) Escribe una consecuencia real de algo que puedes hacer o no hacer esta semana.',
        tip: 'Estructura fija: If + present simple, will + base verb. Nunca digas "If you will study..." — la clausula con if siempre va en presente. Puedes invertir el orden: "I will help if you need me."',
      },
      {
        id: 22,
        slug: 'general-second-conditional',
        title: 'Second Conditional',
        explanation: 'El second conditional se usa para situaciones hipoteticas o imaginarias en el presente o futuro que son poco probables o imposibles. La condicion usa pasado simple (if + subject + past verb) y el resultado usa would + verbo base. Para el verbo to be se recomienda were para todos los sujetos.',
        example: 'If I spoke perfect English, I would get a better job right away. / If she were the manager, she would change the whole process. / What would you do if you lost your job tomorrow? / If I had more time, I would study every day.',
        exercise: 'Responde estas preguntas con second conditional: 1) "What would you do if you won a million dollars?" 2) "Where would you live if you could live anywhere?" 3) "What would you change if you were the CEO of your company?"',
        tip: 'Diferencia clave: first conditional = situacion posible ("If I study..."), second conditional = situacion hipotetica ("If I studied..."). "If I were you, I would apologize" es una expresion muy util para dar consejos.',
      },
      {
        id: 23,
        slug: 'general-third-conditional',
        title: 'Third Conditional',
        explanation: 'El third conditional habla de situaciones pasadas que no ocurrieron y su resultado imaginario. Es imposible cambiarlo porque ya paso. La condicion usa if + had + participio pasado y el resultado usa would have + participio pasado. Se usa para arrepentimientos, criticas o especulaciones sobre el pasado.',
        example: 'If I had prepared better, I would have passed the interview. / She would not have lost the client if she had listened more carefully. / If they had called earlier, we would have solved the problem in time.',
        exercise: 'Piensa en 2 situaciones del pasado que podrian haber sido diferentes y escribelas con third conditional. Ejemplo: "If I had studied English earlier, I would have gotten that job."',
        tip: 'La estructura es larga pero tiene logica: if + had + participio (condicion pasada imposible) + would have + participio (resultado imaginario). Mixed conditional: if + third conditional + second conditional result: "If I had studied, I would be a doctor now."',
      },
      {
        id: 24,
        slug: 'general-passive-voice',
        title: 'Passive Voice',
        explanation: 'La voz pasiva enfoca la atencion en la accion o en quien recibe la accion, no en quien la realiza. Se forma con el verbo to be + participio pasado. Se usa cuando no sabes quien hizo la accion, no es importante quien la hizo, o en contextos formales y reportes profesionales.',
        example: 'The issue was resolved in 10 minutes. / All calls are recorded for quality purposes. / The report has been sent to the manager. / The new policy will be implemented next month. / Mistakes were made during the process.',
        exercise: 'Transforma a voz pasiva: 1) "The team solved the problem." 2) "The manager approved the budget." 3) "They will announce the results tomorrow." 4) "Someone has broken the printer."',
        tip: 'Para transformar: el objeto de la activa se vuelve sujeto de la pasiva. El agente puede omitirse o agregarse con by: "The report was written by the analyst." En contextos laborales la pasiva suena mas formal y objetiva.',
      },
      {
        id: 25,
        slug: 'general-reported-speech',
        title: 'Reported Speech',
        explanation: 'El reported speech (discurso indirecto) se usa para contar lo que alguien dijo sin citar sus palabras exactas. Los tiempos verbales generalmente retroceden un paso: present simple -> past simple, will -> would, can -> could, is -> was. Las referencias de tiempo y lugar tambien cambian.',
        example: 'Direct: "I am working on it." Reported: She said she was working on it. / Direct: "Can you call me back?" Reported: He asked if I could call him back. / Direct: "We will send the report." Reported: They said they would send the report.',
        exercise: 'Convierte al reported speech: 1) "I need help with my account." (The client said...) 2) "We will process your refund tomorrow." (The agent said...) 3) "Can you hold for a moment?" (She asked...)',
        tip: 'Verbos de reporte comunes: said (para afirmaciones), asked (para preguntas), told + person (para instrucciones), explained, mentioned, promised. "He said that..." / "She told me that..." / "They asked whether..."',
      },
      {
        id: 26,
        slug: 'general-past-perfect',
        title: 'Past Perfect',
        explanation: 'El past perfect (had + participio pasado) describe una accion que ocurrio ANTES de otra accion en el pasado. Establece una secuencia temporal clara. Se usa mucho para explicar causas de situaciones pasadas, en reported speech y al narrar eventos en orden no cronologico.',
        example: 'When I arrived at the office, the meeting had already started. / She had never spoken to an angry customer before that call. / By the time we found the solution, the client had already left. / He explained that he had tried everything.',
        exercise: 'Combina estas dos acciones pasadas usando past perfect: 1) "I arrived / the show started" 2) "She called / the client left" 3) "They submitted / the deadline passed" Indica cual ocurrio primero.',
        tip: 'Past perfect = el "pasado del pasado". Si tienes dos acciones pasadas y necesitas mostrar cual fue primero, la primera va en past perfect. "By the time..." y "When..." son conectores muy utiles con este tiempo.',
      },
      {
        id: 27,
        slug: 'general-modals-deduction',
        title: 'Modals of Deduction',
        explanation: 'Los modales de deduccion expresan que tan seguro estas sobre algo en el presente o pasado. Must indica alta certeza (casi seguro). Might / could indica posibilidad (tal vez). Can\'t indica imposibilidad (seguro que no). Para el pasado se agrega have + participio: must have been, might have happened.',
        example: 'He must be the new manager, everyone is greeting him. / She might be in a meeting, I am not sure. / That can\'t be right, I double-checked the numbers. / They must have forgotten the meeting, they are 30 minutes late.',
        exercise: 'Haz deducciones sobre estas situaciones: 1) Tu compa-ero no ha llegado y son las 9 AM. 2) El telefono suena pero nadie contesta. 3) Ves a alguien con muchas maletas. 4) El sistema no responde.',
        tip: 'Must have + participio = deduccion sobre algo que ya ocurrio. "She must have missed the bus" = deduzco que perdio el bus. Might have + participio = posibilidad en el pasado. "He might have forgotten" = tal vez se olvido.',
      },
      {
        id: 28,
        slug: 'general-used-to',
        title: 'Used To',
        explanation: 'Used to + verbo base expresa habitos o situaciones que eran ciertos en el pasado pero que ya no lo son. Implica un contraste entre el pasado y el presente. La negacion es did not use to y la pregunta usa did + subject + use to. No confundir con be used to (estar acostumbrado) ni get used to (acostumbrarse).',
        example: 'I used to be very nervous when speaking English, but now I feel confident. / She used to work night shifts, but now she works mornings. / Did you use to study English at school? / I did not use to like public speaking.',
        exercise: 'Escribe 4 oraciones sobre habitos o situaciones que tenias antes y ahora ya no: "I used to _______ but now I _______." Piensa en trabajo, estudios, hobbies o rutinas.',
        tip: 'Used to solo existe en pasado, no hay "I use to" en presente. Para el presente di: "I usually..." o "I normally...". Be used to = estar acostumbrado: "I am used to working night shifts." Get used to = acostumbrarse: "I am getting used to the new system."',
      },
      {
        id: 29,
        slug: 'general-relative-clauses',
        title: 'Relative Clauses',
        explanation: 'Las clausulas relativas dan informacion adicional sobre una persona o cosa usando who (personas), which (cosas/animales) o that (personas y cosas). Las clausulas definitorias identifican de quien o de que estamos hablando (sin comas). Las no definitorias agregan informacion extra y van entre comas.',
        example: 'The agent who handled my case was very helpful. / This is the software which we use every day. / The report that I sent you needs to be updated. / My manager, who has 10 years of experience, will join the call.',
        exercise: 'Une estas oraciones con who, which o that: 1) "I spoke to a person. She was very rude." 2) "The system crashed. It happened during the call." 3) "The training was excellent. I attended it last week."',
        tip: 'Who y that son intercambiables para personas en el ingles moderno. Which y that son intercambiables para cosas. Pero en clausulas no definitorias (con comas) solo puedes usar who o which, nunca that: "My colleague, who is from Colombia, speaks three languages."',
      },
    ],
  },
];
