const { PrismaClient, Plan, LessonLevel, LessonCategory } = require('@prisma/client');
const { randomBytes, scryptSync } = require('crypto');

const prisma = new PrismaClient();

function hashPassword(password) {
  const salt = randomBytes(16).toString('hex');
  const hash = scryptSync(password, salt, 64).toString('hex');
  return `${salt}:${hash}`;
}

const lessons = [
  // ── Basic 1 / Nivel Inicial ──────────────────────────────────────────────
  {
    slug: 'general-zero-conditional',
    title: 'Zero Conditional',
    description: 'Hechos universales y verdades logicas usando presente simple en ambas clausulas.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 1,
    isPremium: false,
    syllabus: ['Estructura If + present, present', 'Verdades universales', 'Hechos cientificos', 'Reglas generales', 'Practica oral con ejemplos cotidianos'],
  },
  {
    slug: 'general-simple-present',
    title: 'Simple Present (Do/Does)',
    description: 'Uso de auxiliares do/does para preguntas y negaciones en presente simple.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 2,
    isPremium: true,
    syllabus: ['Do/does en preguntas', 'Do not/does not en negaciones', 'Tercera persona singular', 'Adverbios de frecuencia', 'Practica con rutinas diarias'],
  },
  {
    slug: 'general-present-continuous',
    title: 'Present Continuous',
    description: 'Estructuras para acciones que ocurren en este momento.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 3,
    isPremium: true,
    syllabus: ['Am/is/are + verb-ing', 'Acciones en progreso', 'Diferencia con simple present', 'Expresiones de tiempo (now, right now)', 'Preguntas y negaciones'],
  },
  {
    slug: 'general-can-cant',
    title: "Can / Can't",
    description: 'Expresion de habilidades y posibilidades en ingles.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 4,
    isPremium: true,
    syllabus: ['Can para habilidad', "Can't para imposibilidad", 'Preguntas con can', 'Could como forma pasada o cortés', 'Frases utiles en trabajo'],
  },
  {
    slug: 'general-prepositions-place',
    title: 'Prepositions of Place',
    description: 'Uso de in, on, at para indicar ubicacion con precision.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 5,
    isPremium: true,
    syllabus: ['In para espacios cerrados', 'On para superficies', 'At para puntos especificos', 'Combinaciones frecuentes', 'Practica: describir el entorno'],
  },
  {
    slug: 'general-object-pronouns',
    title: 'Object Pronouns',
    description: 'Uso de me, you, him, her, it, us, them en oraciones.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 6,
    isPremium: true,
    syllabus: ['Pronombres de objeto directo', 'Posicion despues del verbo', 'Posicion con preposiciones', 'Diferencia con subject pronouns', 'Practica de sustitucion'],
  },
  {
    slug: 'general-countable-uncountable',
    title: 'Countable and Uncountable Nouns',
    description: 'Diferencia entre sustantivos contables e incontables.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 7,
    isPremium: true,
    syllabus: ['Nouns que se cuentan', 'Nouns que no se cuentan', 'A/an vs some', 'Uso de how much / how many', 'Errores frecuentes'],
  },
  {
    slug: 'general-quantifiers',
    title: 'Quantifiers',
    description: 'Uso de some, any, much, many para expresar cantidad.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 8,
    isPremium: true,
    syllabus: ['Some en afirmativas', 'Any en negativas y preguntas', 'Much para incontables', 'Many para contables', 'A lot of / plenty of'],
  },
  {
    slug: 'general-possessive-adjectives',
    title: 'Possessive Adjectives',
    description: 'My, your, his, her, its, our, their para indicar posesion.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 9,
    isPremium: true,
    syllabus: ['Lista completa de adjetivos posesivos', 'Posicion antes del noun', 'Diferencia con possessive pronouns', 'Practica con objetos cotidianos', 'Errores comunes'],
  },
  {
    slug: 'general-verb-to-be',
    title: 'Verb To Be',
    description: 'Formas basicas de am, is, are en presente: identidad y estado.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 10,
    isPremium: true,
    syllabus: ['Am/is/are en afirmativo', 'Negaciones con not', 'Preguntas invirtiendo orden', 'Contracciones', 'Errores frecuentes con to be'],
  },
  // ── Basic 2 ──────────────────────────────────────────────────────────────
  {
    slug: 'general-simple-past',
    title: 'Simple Past (Did)',
    description: 'Uso del auxiliar did y verbos regulares e irregulares en pasado.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 11,
    isPremium: true,
    syllabus: ['Verbos regulares en pasado (-ed)', 'Verbos irregulares comunes', 'Did en preguntas', 'Did not en negaciones', 'Marcadores de tiempo pasado'],
  },
  {
    slug: 'general-past-continuous',
    title: 'Past Continuous',
    description: 'Acciones progresivas en el pasado con was/were + ing.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 12,
    isPremium: true,
    syllabus: ['Was/were + verb-ing', 'Acciones en progreso en el pasado', 'Combinar con simple past', 'When y while como conectores', 'Practica de narracion'],
  },
  {
    slug: 'general-be-going-to',
    title: 'Be Going To',
    description: 'Expresion de planes y futuro proximo ya decidido.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 13,
    isPremium: true,
    syllabus: ['Estructura am/is/are going to', 'Planes con evidencia visible', 'Diferencia con will', 'Preguntas y negaciones', 'Practica de planes personales'],
  },
  {
    slug: 'general-will-future',
    title: 'Will for Future',
    description: 'Promesas, decisiones espontaneas y predicciones con will.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 14,
    isPremium: true,
    syllabus: ['Will para decisiones del momento', 'Promesas con will', 'Predicciones sin evidencia', 'Shall como alternativa formal', 'Contracciones con will'],
  },
  {
    slug: 'general-comparative-adjectives',
    title: 'Comparative Adjectives',
    description: 'Reglas para comparar dos objetos o personas en ingles.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 15,
    isPremium: true,
    syllabus: ['Adjetivos cortos: -er + than', 'Adjetivos largos: more + adj', 'Irregular: good/better, bad/worse', 'As + adj + as para igualdad', 'Practica con objetos del entorno'],
  },
  // ── Basic 3 ──────────────────────────────────────────────────────────────
  {
    slug: 'general-present-perfect',
    title: 'Present Perfect',
    description: 'Uso de have/has + participio pasado para experiencias y resultados.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 16,
    isPremium: true,
    syllabus: ['Have/has + past participle', 'Ever/never para experiencias', 'Just para acciones recientes', 'Present perfect vs simple past', 'Practica de experiencias personales'],
  },
  {
    slug: 'general-superlative-adjectives',
    title: 'Superlative Adjectives',
    description: 'Destacar el elemento extremo de un grupo.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 17,
    isPremium: true,
    syllabus: ['The + adjetivo corto + -est', 'The most + adjetivo largo', 'Irregulares: best, worst, most', 'Uso en contextos laborales', 'Practica con ranking de opciones'],
  },
  {
    slug: 'general-adverbs-manner',
    title: 'Adverbs of Manner',
    description: 'Como realizar acciones: quickly, carefully, clearly.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 18,
    isPremium: true,
    syllabus: ['Formacion con -ly', 'Adverbios irregulares (fast, hard)', 'Posicion en la oracion', 'Uso para sonar profesional', 'Practica en descripciones de trabajo'],
  },
  {
    slug: 'general-should-shouldnt',
    title: "Should / Shouldn't",
    description: 'Dar consejos y sugerencias con should en contextos cotidianos.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 19,
    isPremium: true,
    syllabus: ['Should para recomendaciones', "Shouldn't para advertencias", 'Diferencia con must', 'Preguntas con should', 'Practica dando consejos laborales'],
  },
  {
    slug: 'general-present-perfect-reinforcement',
    title: 'Present Perfect (Refuerzo)',
    description: 'Refuerzo con already, yet, since y for en contextos reales.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 20,
    isPremium: true,
    syllabus: ['Already en afirmativas', 'Yet en negativas y preguntas', 'Since para punto de inicio', 'For para duracion', 'Practica: reporte de avances'],
  },
  // ── Intermediate and Advanced ────────────────────────────────────────────
  {
    slug: 'general-first-conditional',
    title: 'First Conditional',
    description: 'Situaciones reales o posibles en el futuro.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 21,
    isPremium: true,
    syllabus: ['If + present simple, will + verb', 'Situaciones probables', 'Unless como alternativa', 'Preguntas con first conditional', 'Practica en escenarios laborales'],
  },
  {
    slug: 'general-second-conditional',
    title: 'Second Conditional',
    description: 'Situaciones hipoteticas o imaginarias en el presente.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 22,
    isPremium: true,
    syllabus: ['If + past simple, would + verb', 'Were para todos los sujetos', 'Hipotesis poco probables', 'Consejos con I would', 'Practica con situaciones imaginarias'],
  },
  {
    slug: 'general-third-conditional',
    title: 'Third Conditional',
    description: 'Arrepentimientos y situaciones imposibles del pasado.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 23,
    isPremium: true,
    syllabus: ['If + had + participle, would have + participle', 'Arrepentimientos pasados', 'Diferencia con second conditional', 'Mixed conditionals basico', 'Practica de reflexion profesional'],
  },
  {
    slug: 'general-passive-voice',
    title: 'Passive Voice',
    description: 'Enfoque en la accion mas que en quien la realiza.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 24,
    isPremium: true,
    syllabus: ['To be + past participle', 'Presente y pasado en pasiva', 'Cuando usar pasiva', 'By para indicar agente', 'Practica en reportes y documentacion'],
  },
  {
    slug: 'general-reported-speech',
    title: 'Reported Speech',
    description: 'Como contar lo que alguien mas dijo con backshift.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 25,
    isPremium: true,
    syllabus: ['Said/told en reported speech', 'Backshift de tiempos verbales', 'Reported questions', 'Reported commands', 'Practica: resumir conversaciones de trabajo'],
  },
  {
    slug: 'general-past-perfect',
    title: 'Past Perfect',
    description: 'Acciones que ocurrieron antes de otra accion en el pasado.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 26,
    isPremium: true,
    syllabus: ['Had + past participle', 'Secuencia de eventos pasados', 'Already/just/never con past perfect', 'Combinacion con simple past', 'Practica de narracion de incidentes'],
  },
  {
    slug: 'general-modals-deduction',
    title: 'Modals of Deduction',
    description: "Uso de must, might, can't para suposiciones y deducciones.",
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 27,
    isPremium: true,
    syllabus: ['Must para certeza alta', 'Might/could para posibilidad', "Can't para imposibilidad", 'Deduccion en presente y pasado', 'Practica con situaciones laborales'],
  },
  {
    slug: 'general-used-to',
    title: 'Used To',
    description: 'Habitos o estados del pasado que ya no son ciertos.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 28,
    isPremium: true,
    syllabus: ['Used to + verb base', 'Negacion: did not use to', 'Preguntas con did you use to', 'Be used to / get used to', 'Practica de cambios profesionales'],
  },
  {
    slug: 'general-relative-clauses',
    title: 'Relative Clauses',
    description: 'Uso de who, which, that para dar informacion adicional.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 29,
    isPremium: true,
    syllabus: ['Who para personas', 'Which para cosas', 'That para ambos', 'Clausulas definitorias vs no definitorias', 'Practica: describir roles y procesos'],
  },
  {
    slug: 'call-center-opening-script',
    title: 'CC Basic 1 · Opening y verificacion',
    description: 'Apertura profesional con control y tono confiable.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 1,
    isPremium: true,
    syllabus: [
      'Greeting profesional',
      'Identificacion del agente',
      'Nombre de la empresa',
      'Motivo de la llamada',
      'Verificacion de seguridad',
      'Pedir datos sin friccion',
      'Frases de cortesia clave',
      'Control de ritmo de apertura',
      'Preguntas abiertas iniciales',
      'Evitar frases bruscas',
      'Role-play de opening',
      'Checklist de inicio perfecto',
    ],
  },
  {
    slug: 'call-center-data-verification',
    title: 'CC Basic 1 · Confirmacion de datos',
    description: 'Valida informacion sensible con seguridad y empatia.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 2,
    isPremium: true,
    syllabus: [
      'Politica basica de seguridad',
      'Preguntas de verificacion',
      'Datos permitidos y no permitidos',
      'Manejo de cliente apurado',
      'Cliente que se niega a validar',
      'Alternativas de confirmacion',
      'Explicar el por que',
      'Registro correcto del dato',
      'Frases de transicion',
      'Confirmacion final',
      'Practica con 5 escenarios',
      'Rubrica de cumplimiento',
    ],
  },
  {
    slug: 'call-center-discovery-questions',
    title: 'CC Basic 1 · Sondeo y preguntas de diagnostico',
    description: 'Haz preguntas utiles para identificar la causa raiz.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 3,
    isPremium: true,
    syllabus: [
      'Preguntas abiertas vs cerradas',
      'Secuencia de diagnostico',
      'Recopilar contexto minimo',
      'Confirmar problema principal',
      'Parafrasear para validar',
      'Evitar preguntas ambiguas',
      'Detectar informacion faltante',
      'Priorizar sintomas',
      'Resumen de hallazgos',
      'Transicion a solucion',
      'Caso guiado de troubleshooting',
      'Checklist de diagnostico',
    ],
  },
  {
    slug: 'call-center-objections',
    title: 'CC Basic 2 · Objeciones y desescalada',
    description: 'Responde objeciones sin confrontar y manteniendo control.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 4,
    isPremium: true,
    syllabus: [
      'Escucha activa',
      'Empatia real en 1 frase',
      'Acknowledge + Clarify + Resolve',
      'Objecion por precio',
      'Objecion por tiempo',
      'Objecion por politica',
      'Objecion por experiencias pasadas',
      'Bajar tono emocional',
      'Proponer alternativa viable',
      'Confirmar aceptacion',
      'Role-play de cliente molesto',
      'Autoevaluacion de desescalada',
    ],
  },
  {
    slug: 'call-center-hold-and-transfer',
    title: 'CC Basic 2 · Hold y transferencias',
    description: 'Poner en espera y transferir sin perder confianza del cliente.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 5,
    isPremium: true,
    syllabus: [
      'Solicitar permiso para hold',
      'Explicar motivo de espera',
      'Tiempo estimado realista',
      'Retomar llamada correctamente',
      'Transferencia en frio vs caliente',
      'Handoff con contexto completo',
      'Frases de enlace profesional',
      'Reducir repeticion para cliente',
      'Confirmar nuevo responsable',
      'Cierre parcial antes de transferir',
      'Simulacion de transferencia',
      'Checklist de handoff',
    ],
  },
  {
    slug: 'call-center-escalations',
    title: 'CC Basic 2 · Escalaciones y SLA',
    description: 'Escala casos con trazabilidad y expectativas claras.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 6,
    isPremium: true,
    syllabus: [
      'Criterios de escalacion',
      'SLA y tiempos comprometidos',
      'Explicar por que se escala',
      'Que informacion documentar',
      'Escalacion tecnica',
      'Escalacion de facturacion',
      'Gestionar frustracion del cliente',
      'Promesas realistas',
      'Seguimiento post-escalacion',
      'Evitar abandono del caso',
      'Caso complejo end-to-end',
      'Checklist de escalacion limpia',
    ],
  },
  {
    slug: 'call-center-refunds-billing',
    title: 'CC Basic 3 · Facturacion y reembolsos',
    description: 'Comunica cargos, ajustes y devoluciones con precision.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 7,
    isPremium: true,
    syllabus: [
      'Vocabulario de billing',
      'Explicar un cargo',
      'Validar politica de refund',
      'Casos elegibles/no elegibles',
      'Plazos de reembolso',
      'Empatia en temas de dinero',
      'Evitar lenguaje defensivo',
      'Confirmar montos y fechas',
      'Escalar casos financieros',
      'Plantillas de respuesta',
      'Role-play de reclamo de cobro',
      'Checklist de cierre financiero',
    ],
  },
  {
    slug: 'call-center-technical-troubleshooting',
    title: 'CC Basic 3 · Troubleshooting tecnico',
    description: 'Guia pasos tecnicos de forma simple y ordenada.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 8,
    isPremium: true,
    syllabus: [
      'Lenguaje tecnico simplificado',
      'Secuencia de troubleshooting',
      'Comandos de verificacion basicos',
      'Explicar cada paso',
      'Confirmar resultado de prueba',
      'Plan B si falla',
      'Escalar con evidencia tecnica',
      'Resumen de acciones realizadas',
      'Manejo de cliente no tecnico',
      'Evitar saturar de informacion',
      'Caso guiado de soporte',
      'Checklist de solucion tecnica',
    ],
  },
  {
    slug: 'call-center-de-escalation-advanced',
    title: 'CC Intermediate · De-escalation avanzada',
    description: 'Controla interacciones de alta tension sin perder calidad.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 9,
    isPremium: true,
    syllabus: [
      'Detectar gatillos de conflicto',
      'Frases para bajar intensidad',
      'Escucha reflexiva',
      'Reencuadre de problema',
      'Marcar limites con respeto',
      'Evitar frases incendiarias',
      'Negociar soluciones intermedias',
      'Compromisos medibles',
      'Cerrar con control emocional',
      'Seguimiento preventivo',
      'Simulacion de cliente hostil',
      'Rubrica de manejo emocional',
    ],
  },
  {
    slug: 'call-center-retention-save',
    title: 'CC Intermediate · Retencion y save offers',
    description: 'Reduce cancelaciones con argumentos claros y eticos.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 10,
    isPremium: true,
    syllabus: [
      'Causas tipicas de cancelacion',
      'Preguntas de retencion',
      'Propuesta de valor personalizada',
      'Ofertas de retencion permitidas',
      'Manejo de no inicial',
      'Negociacion sin presion',
      'Cuando aceptar la baja',
      'Cerrar con buena experiencia',
      'Documentacion de retencion',
      'Metricas basicas de save rate',
      'Role-play de churn risk',
      'Checklist de retencion etica',
    ],
  },
  {
    slug: 'call-center-qa-compliance',
    title: 'CC Intermediate · QA y compliance',
    description: 'Habla con calidad auditada y cumplimiento de politicas.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 11,
    isPremium: true,
    syllabus: [
      'Criterios de calidad de llamada',
      'Frases obligatorias',
      'Avisos legales basicos',
      'Evitar promesas indebidas',
      'Privacidad y datos sensibles',
      'Estructura de llamada auditada',
      'Control de tiempos',
      'Documentacion post-llamada',
      'Errores criticos de compliance',
      'Autochequeo de QA',
      'Revision de caso grabado',
      'Plan de mejora mensual',
    ],
  },
  {
    slug: 'call-center-closing-followup',
    title: 'CC Intermediate · Cierre y follow-up',
    description: 'Cierra llamadas con acuerdos claros y siguiente paso definido.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 12,
    isPremium: true,
    syllabus: [
      'Resumen final de solucion',
      'Confirmar entendimiento del cliente',
      'Proximo paso y responsable',
      'Canal de seguimiento',
      'Tiempo de respuesta esperado',
      'Frases de despedida profesional',
      'Invitar a feedback',
      'Evitar cierres abruptos',
      'Reducir recontacto',
      'Registro final del caso',
      'Role-play de cierre completo',
      'Checklist de salida impecable',
    ],
  },
  // ── CC Interview ─────────────────────────────────────────────────────────
  {
    slug: 'cci-self-introduction',
    title: 'Self-Introduction for CC Jobs',
    description: 'Presenta tu perfil con claridad y confianza en la primera pregunta de la entrevista.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CC_INTERVIEW,
    order: 1,
    isPremium: true,
    syllabus: [
      'Estructura: nombre + experiencia + objetivo',
      'Duracion ideal: 60-90 segundos',
      'Frases de apertura profesional',
      'Mencionar habilidades de idioma',
      'Conectar tu perfil con el rol CC',
      'Evitar informacion irrelevante',
      'Tono confiado sin sonar memorizado',
      'Practica de presentacion en voz alta',
    ],
  },
  {
    slug: 'cci-motivation',
    title: 'Why Do You Want This Job?',
    description: 'Responde la pregunta de motivacion con autenticidad y enfoque en el rol.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CC_INTERVIEW,
    order: 2,
    isPremium: true,
    syllabus: [
      'Estructura: razon + habilidad + aporte',
      'Evitar respuestas genericas',
      'Conectar interes con la empresa',
      'Mostrar conocimiento del rol CC',
      'Frases de entusiasmo genuino',
      'Practica con ejemplos reales',
      'Respuesta de 45-60 segundos',
      'Checklist de motivacion convincente',
    ],
  },
  {
    slug: 'cci-customer-mindset',
    title: 'Customer Service Mindset & Empathy',
    description: 'Demuestra orientacion al cliente y capacidad empatica en la entrevista.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CC_INTERVIEW,
    order: 3,
    isPremium: true,
    syllabus: [
      'Que es orientacion al cliente',
      'Frases de empatia en ingles',
      'Ejemplo real de buena atencion',
      'Diferencia entre empatia y simpatia',
      'Como expresar paciencia',
      'Vocabulario de servicio al cliente',
      'Preguntas tipicas sobre actitud',
      'Practica con mini-respuestas',
    ],
  },
  {
    slug: 'cci-stress-handling',
    title: 'Handling Stress & Difficult Situations',
    description: 'Responde preguntas sobre presion, clientes dificiles y situaciones de alta carga.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CC_INTERVIEW,
    order: 4,
    isPremium: true,
    syllabus: [
      'Preguntas tipicas sobre estres',
      'Vocabulario de manejo de presion',
      'Ejemplo real con cliente dificil',
      'Estructura: situacion + accion + resultado',
      'Frases para describir resolucion',
      'Como mostrar estabilidad emocional',
      'Evitar respuestas negativas',
      'Role-play de situacion critica',
    ],
  },
  {
    slug: 'cci-english-fluency',
    title: 'Demonstrating Your English Fluency',
    description: 'Estrategias para mostrar tu nivel de ingles con claridad y naturalidad.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CC_INTERVIEW,
    order: 5,
    isPremium: true,
    syllabus: [
      'Ritmo y entonacion en entrevista',
      'Como recuperarse de un error',
      'Expresiones de precision verbal',
      'Evitar muletillas en ingles',
      'Confirmar que fuiste entendido',
      'Pausas estrategicas al hablar',
      'Vocabulario de profesionalismo',
      'Practica de fluencia oral',
    ],
  },
  {
    slug: 'cci-star-method',
    title: 'Situational Questions: The STAR Method',
    description: 'Estructura respuestas situacionales con el metodo STAR para impresionar al entrevistador.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CC_INTERVIEW,
    order: 6,
    isPremium: true,
    syllabus: [
      'Situacion, Tarea, Accion, Resultado',
      'Preguntas tipicas tipo STAR',
      'Como elegir el ejemplo correcto',
      'Duracion ideal de la respuesta',
      'Conectores para la narrativa',
      'Evitar respuestas vagas',
      'Practica con 3 escenarios CC',
      'Checklist de respuesta STAR',
    ],
  },
  {
    slug: 'cci-availability',
    title: 'Schedule, Shift Flexibility & Availability',
    description: 'Comunica tu disponibilidad y flexibilidad de turno de forma clara y positiva.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CC_INTERVIEW,
    order: 7,
    isPremium: true,
    syllabus: [
      'Vocabulario de turnos y horarios',
      'Como expresar disponibilidad',
      'Responder preguntas de horario',
      'Frases para mostrar flexibilidad',
      'Negociar sin sonar negativo',
      'Dias, horas y turnos en ingles',
      'Confirmar compromisos de horario',
      'Practica de dialogo de disponibilidad',
    ],
  },
  {
    slug: 'cci-interview-closing',
    title: 'Questions to Ask & Closing Strong',
    description: 'Cierra la entrevista con preguntas inteligentes y una despedida que deja impacto.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CC_INTERVIEW,
    order: 8,
    isPremium: true,
    syllabus: [
      'Por que preguntar al entrevistador',
      '5 preguntas recomendadas para CC',
      'Preguntas que debes evitar',
      'Frase de cierre con confianza',
      'Agradecer la oportunidad',
      'Reafirmar tu interes en el puesto',
      'Proximos pasos del proceso',
      'Practica de cierre completo',
    ],
  },
];

async function main() {
  const premiumEmail = process.env.SEED_PREMIUM_EMAIL || 'premium@hablaspeak.com';
  const premiumPassword = process.env.SEED_PREMIUM_PASSWORD || 'Premium123!';
  const freeEmail = process.env.SEED_FREE_EMAIL || 'demo@hablaspeak.com';
  const freePassword = process.env.SEED_FREE_PASSWORD || 'Demo123!';

  await prisma.user.upsert({
    where: { email: premiumEmail },
    update: {
      name: 'Premium Tester',
      hashedPassword: hashPassword(premiumPassword),
      plan: Plan.PREMIUM,
    },
    create: {
      email: premiumEmail,
      name: 'Premium Tester',
      hashedPassword: hashPassword(premiumPassword),
      plan: Plan.PREMIUM,
      streakCurrent: 3,
    },
  });

  await prisma.user.upsert({
    where: { email: freeEmail },
    update: {
      name: 'Free Tester',
      hashedPassword: hashPassword(freePassword),
      plan: Plan.FREE,
    },
    create: {
      email: freeEmail,
      name: 'Free Tester',
      hashedPassword: hashPassword(freePassword),
      plan: Plan.FREE,
      streakCurrent: 1,
    },
  });

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { slug: lesson.slug },
      update: lesson,
      create: lesson,
    });
  }

  // ── 20 usuarios premium para clientes ────────────────────────────────────
  const CLIENT_PASSWORDS = [
    'Kx9#mPqL2w', 'Rn7$vBzY4t', 'Jm3@wKpX8n', 'Qv6!tHcN5s', 'Yz4$bFkW9r',
    'Lp8#nGdR3x', 'Th2@sVmJ6q', 'Wb5!cXeK7f', 'Ng3$kZpM4h', 'Fd7#yRtB2v',
    'Hc9@mWsQ8n', 'Xp4!bLkF6t', 'Vr6$zNgT3w', 'Mk8#qJdP5y', 'Bs2@nCxH7r',
    'Zt5!wMvK9s', 'Ep7$fRnB4q', 'Gw3#kYmL8c', 'Jn6@tXpF2v', 'Cr9!sHzW5b',
  ];

  const clientCredentials = [];
  for (let i = 1; i <= 20; i++) {
    const n = String(i).padStart(2, '0');
    const email = `cliente${n}@hablaspeak.com`;
    const password = CLIENT_PASSWORDS[i - 1];
    await prisma.user.upsert({
      where: { email },
      update: {
        plan: Plan.PREMIUM,
      },
      create: {
        email,
        name: `Cliente ${n}`,
        hashedPassword: hashPassword(password),
        plan: Plan.PREMIUM,
        streakCurrent: 0,
      },
    });
    clientCredentials.push({ email, password });
  }

  console.log('\n' + '═'.repeat(55));
  console.log('  USUARIOS PREMIUM HABLASPEAK');
  console.log('═'.repeat(55));
  for (const { email, password } of clientCredentials) {
    console.log(`  ${email.padEnd(32)} |  ${password}`);
  }
  console.log('═'.repeat(55) + '\n');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async error => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
