const { PrismaClient, Plan, LessonLevel, LessonCategory } = require('@prisma/client');
const { randomBytes, scryptSync } = require('crypto');

const prisma = new PrismaClient();

function hashPassword(password) {
  const salt = randomBytes(16).toString('hex');
  const hash = scryptSync(password, salt, 64).toString('hex');
  return `${salt}:${hash}`;
}

const lessons = [
  {
    slug: 'beginner-greetings',
    title: 'Basic 1 · Pronombres y verbo to be',
    description: 'Base para presentarte con estructura correcta y respuestas cortas.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 1,
    isPremium: false,
    syllabus: [
      'Pronombres personales (I, you, he, she, it, we, they)',
      'Verbo to be: am/is/are',
      'Afirmativo, negativo e interrogativo con to be',
      'Respuestas cortas (Yes, I am / No, she is not)',
      'Contracciones basicas (I am -> I\'m)',
      'Errores frecuentes con am/is/are',
      'Presentacion personal en 5 lineas',
      'Drill de 12 oraciones con to be',
    ],
  },
  {
    slug: 'beginner-daily-routines',
    title: 'Basic 1 · Rutinas y presente simple',
    description: 'Habla de habitos diarios con verbos de uso frecuente.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 2,
    isPremium: false,
    syllabus: [
      'Presente simple con I/you/we/they',
      'Regla de tercera persona (he/she/it + s/es)',
      'Do/does en preguntas',
      'Do not/does not en negaciones',
      'Adverbios de frecuencia (always, usually, often...)',
      'Rutinas diarias por bloques de tiempo',
      'Errores comunes de tercera persona',
      'Mini speaking: describe tu dia',
    ],
  },
  {
    slug: 'beginner-time-dates',
    title: 'Basic 1 · Hora, fechas y calendario',
    description: 'Expresa horarios, dias y fechas sin confusiones.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 3,
    isPremium: true,
    syllabus: [
      'How to tell the time (hora en ingles)',
      'Dias, meses y fechas',
      'Preposiciones de tiempo: in / on / at',
      'From...to... y rangos de horario',
      'Preguntas de fecha y hora',
      'Errores tipicos con fechas',
      'Practica: agendar reunion',
      'Role-play: confirmar cita',
    ],
  },
  {
    slug: 'beginner-questions-answers',
    title: 'Basic 1 · Preguntas y respuestas utiles',
    description: 'Formula preguntas claras para obtener informacion.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.GENERAL,
    order: 4,
    isPremium: true,
    syllabus: [
      'Yes/No questions con to be y do/does',
      'Wh-questions: what, where, when, why, how',
      'Orden correcto en pregunta',
      'Short answers naturales',
      'Preguntas de seguimiento (follow-up)',
      'Entonacion al preguntar',
      'Preguntas para entrevista basica',
      'Drill de 20 preguntas',
    ],
  },
  {
    slug: 'intermediate-work-communication',
    title: 'Basic 2 · Present, past y future',
    description: 'Conecta presente, pasado y futuro en conversaciones laborales.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 5,
    isPremium: true,
    syllabus: [
      'Present simple vs present continuous',
      'Past simple: regulares e irregulares',
      'Future con will',
      'Future con going to',
      'Marcadores de tiempo (yesterday, now, tomorrow)',
      'Preguntas en presente, pasado y futuro',
      'Errores de auxiliar en preguntas',
      'Practica guiada de entrevista',
    ],
  },
  {
    slug: 'intermediate-modals-work',
    title: 'Basic 2 · Will, modales y tono profesional',
    description: 'Usa can, could, should, must para sonar profesional.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 6,
    isPremium: true,
    syllabus: [
      'Will para decisiones rapidas y promesas',
      'Can/could para habilidad y peticiones',
      'Should para recomendaciones',
      'Must/have to para obligacion',
      'May/might para posibilidad',
      'Would para tono cortés',
      'Frases profesionales para call/work',
      'Role-play de soporte y seguimiento',
    ],
  },
  {
    slug: 'intermediate-perfect-basics',
    title: 'Basic 2 · Present perfect aplicado',
    description: 'Expresa experiencia y resultados recientes con claridad.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 7,
    isPremium: true,
    syllabus: [
      'Estructura: have/has + past participle',
      'Ever/never para experiencia',
      'Already/yet para estado de tarea',
      'Since/for para duracion',
      'Present perfect vs past simple',
      'Reportar avances recientes',
      'Errores comunes de participio',
      'Mini reporte semanal en ingles',
    ],
  },
  {
    slug: 'intermediate-email-chat-english',
    title: 'Basic 3 · Linking words y coherencia',
    description: 'Escribe mensajes profesionales, breves y accionables.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.GENERAL,
    order: 8,
    isPremium: true,
    syllabus: [
      'Conectores de secuencia (first, then, finally)',
      'Conectores de contraste (but, however, although)',
      'Conectores de causa y resultado (because, so, therefore)',
      'Coherencia entre oraciones',
      'Evitar repeticiones y fillers',
      'Parrafos cortos y claros',
      'Practica de respuesta de 60-90 segundos',
      'Reescritura de respuestas poco claras',
    ],
  },
  {
    slug: 'advanced-problem-solving',
    title: 'Basic 3 · Condicionales y solucion de problemas',
    description: 'Explica escenarios, riesgos y acciones con mas precision.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 9,
    isPremium: true,
    syllabus: [
      'Zero conditional (hechos y reglas)',
      'First conditional (situaciones reales futuras)',
      'Second conditional (hipotesis)',
      'Third conditional (hipotesis del pasado)',
      'If + clause orden y puntuacion',
      'Condicionales en solucion de problemas',
      'Errores frecuentes en if clauses',
      'Caso practico end-to-end',
    ],
  },
  {
    slug: 'advanced-passive-reported',
    title: 'Intermediate/Advanced · Pasiva y reported speech',
    description: 'Resume incidentes y conversaciones con estructura formal.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 10,
    isPremium: true,
    syllabus: [
      'Voz pasiva en presente, pasado y futuro',
      'Cuando usar pasiva en contexto laboral',
      'Reported speech afirmativo',
      'Reported speech en preguntas',
      'Cambios de tiempo verbal en reported speech',
      'Resumir llamadas y reuniones',
      'Errores comunes de estructura',
      'Practica: transformar activa a pasiva',
    ],
  },
  {
    slug: 'advanced-linking-fluency',
    title: 'Intermediate/Advanced · Used to y estructuras avanzadas',
    description: 'Une ideas con naturalidad para respuestas mas solidas.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 11,
    isPremium: true,
    syllabus: [
      'Used to para habitos del pasado',
      'Be used to + noun/verb-ing',
      'Get used to + noun/verb-ing',
      'Comparar pasado vs presente',
      'To vs for en contextos frecuentes',
      'Preposiciones avanzadas de uso comun',
      'Errores frecuentes con used to',
      'Practica: historia de cambio profesional',
    ],
  },
  {
    slug: 'advanced-interview-mastery',
    title: 'Intermediate/Advanced · Mastery de entrevista',
    description: 'Integra gramatica, estructura y estrategia de respuesta.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.GENERAL,
    order: 12,
    isPremium: true,
    syllabus: [
      'Repaso integrado: present/past/future',
      'Repaso integrado: will, modales y condicionales',
      'Repaso integrado: present perfect, passive, reported speech',
      'Framework STAR para respuestas largas',
      'Preguntas conductuales frecuentes',
      'Errores gramaticales que afectan claridad',
      'Simulacion completa de entrevista',
      'Plan de practica de 30 dias',
    ],
  },
  {
    slug: 'call-center-opening-script',
    title: 'CC Basic 1 · Opening y verificacion',
    description: 'Apertura profesional con control y tono confiable.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 1,
    isPremium: true,
    syllabus: [
      'Greeting profesional',
      'Identificacion del agente',
      'Nombre de la empresa',
      'Motivo de la llamada',
      'Verificacion de seguridad',
      'Pedir datos sin friccion',
      'Frases de cortesia clave',
      'Control de ritmo de apertura',
      'Preguntas abiertas iniciales',
      'Evitar frases bruscas',
      'Role-play de opening',
      'Checklist de inicio perfecto',
    ],
  },
  {
    slug: 'call-center-data-verification',
    title: 'CC Basic 1 · Confirmacion de datos',
    description: 'Valida informacion sensible con seguridad y empatia.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 2,
    isPremium: true,
    syllabus: [
      'Politica basica de seguridad',
      'Preguntas de verificacion',
      'Datos permitidos y no permitidos',
      'Manejo de cliente apurado',
      'Cliente que se niega a validar',
      'Alternativas de confirmacion',
      'Explicar el por que',
      'Registro correcto del dato',
      'Frases de transicion',
      'Confirmacion final',
      'Practica con 5 escenarios',
      'Rubrica de cumplimiento',
    ],
  },
  {
    slug: 'call-center-discovery-questions',
    title: 'CC Basic 1 · Sondeo y preguntas de diagnostico',
    description: 'Haz preguntas utiles para identificar la causa raiz.',
    level: LessonLevel.BEGINNER,
    category: LessonCategory.CALL_CENTER,
    order: 3,
    isPremium: true,
    syllabus: [
      'Preguntas abiertas vs cerradas',
      'Secuencia de diagnostico',
      'Recopilar contexto minimo',
      'Confirmar problema principal',
      'Parafrasear para validar',
      'Evitar preguntas ambiguas',
      'Detectar informacion faltante',
      'Priorizar sintomas',
      'Resumen de hallazgos',
      'Transicion a solucion',
      'Caso guiado de troubleshooting',
      'Checklist de diagnostico',
    ],
  },
  {
    slug: 'call-center-objections',
    title: 'CC Basic 2 · Objeciones y desescalada',
    description: 'Responde objeciones sin confrontar y manteniendo control.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 4,
    isPremium: true,
    syllabus: [
      'Escucha activa',
      'Empatia real en 1 frase',
      'Acknowledge + Clarify + Resolve',
      'Objecion por precio',
      'Objecion por tiempo',
      'Objecion por politica',
      'Objecion por experiencias pasadas',
      'Bajar tono emocional',
      'Proponer alternativa viable',
      'Confirmar aceptacion',
      'Role-play de cliente molesto',
      'Autoevaluacion de desescalada',
    ],
  },
  {
    slug: 'call-center-hold-and-transfer',
    title: 'CC Basic 2 · Hold y transferencias',
    description: 'Poner en espera y transferir sin perder confianza del cliente.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 5,
    isPremium: true,
    syllabus: [
      'Solicitar permiso para hold',
      'Explicar motivo de espera',
      'Tiempo estimado realista',
      'Retomar llamada correctamente',
      'Transferencia en frio vs caliente',
      'Handoff con contexto completo',
      'Frases de enlace profesional',
      'Reducir repeticion para cliente',
      'Confirmar nuevo responsable',
      'Cierre parcial antes de transferir',
      'Simulacion de transferencia',
      'Checklist de handoff',
    ],
  },
  {
    slug: 'call-center-escalations',
    title: 'CC Basic 2 · Escalaciones y SLA',
    description: 'Escala casos con trazabilidad y expectativas claras.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 6,
    isPremium: true,
    syllabus: [
      'Criterios de escalacion',
      'SLA y tiempos comprometidos',
      'Explicar por que se escala',
      'Que informacion documentar',
      'Escalacion tecnica',
      'Escalacion de facturacion',
      'Gestionar frustracion del cliente',
      'Promesas realistas',
      'Seguimiento post-escalacion',
      'Evitar abandono del caso',
      'Caso complejo end-to-end',
      'Checklist de escalacion limpia',
    ],
  },
  {
    slug: 'call-center-refunds-billing',
    title: 'CC Basic 3 · Facturacion y reembolsos',
    description: 'Comunica cargos, ajustes y devoluciones con precision.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 7,
    isPremium: true,
    syllabus: [
      'Vocabulario de billing',
      'Explicar un cargo',
      'Validar politica de refund',
      'Casos elegibles/no elegibles',
      'Plazos de reembolso',
      'Empatia en temas de dinero',
      'Evitar lenguaje defensivo',
      'Confirmar montos y fechas',
      'Escalar casos financieros',
      'Plantillas de respuesta',
      'Role-play de reclamo de cobro',
      'Checklist de cierre financiero',
    ],
  },
  {
    slug: 'call-center-technical-troubleshooting',
    title: 'CC Basic 3 · Troubleshooting tecnico',
    description: 'Guia pasos tecnicos de forma simple y ordenada.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 8,
    isPremium: true,
    syllabus: [
      'Lenguaje tecnico simplificado',
      'Secuencia de troubleshooting',
      'Comandos de verificacion basicos',
      'Explicar cada paso',
      'Confirmar resultado de prueba',
      'Plan B si falla',
      'Escalar con evidencia tecnica',
      'Resumen de acciones realizadas',
      'Manejo de cliente no tecnico',
      'Evitar saturar de informacion',
      'Caso guiado de soporte',
      'Checklist de solucion tecnica',
    ],
  },
  {
    slug: 'call-center-de-escalation-advanced',
    title: 'CC Intermediate · De-escalation avanzada',
    description: 'Controla interacciones de alta tension sin perder calidad.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 9,
    isPremium: true,
    syllabus: [
      'Detectar gatillos de conflicto',
      'Frases para bajar intensidad',
      'Escucha reflexiva',
      'Reencuadre de problema',
      'Marcar limites con respeto',
      'Evitar frases incendiarias',
      'Negociar soluciones intermedias',
      'Compromisos medibles',
      'Cerrar con control emocional',
      'Seguimiento preventivo',
      'Simulacion de cliente hostil',
      'Rubrica de manejo emocional',
    ],
  },
  {
    slug: 'call-center-retention-save',
    title: 'CC Intermediate · Retencion y save offers',
    description: 'Reduce cancelaciones con argumentos claros y eticos.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 10,
    isPremium: true,
    syllabus: [
      'Causas tipicas de cancelacion',
      'Preguntas de retencion',
      'Propuesta de valor personalizada',
      'Ofertas de retencion permitidas',
      'Manejo de no inicial',
      'Negociacion sin presion',
      'Cuando aceptar la baja',
      'Cerrar con buena experiencia',
      'Documentacion de retencion',
      'Metricas basicas de save rate',
      'Role-play de churn risk',
      'Checklist de retencion etica',
    ],
  },
  {
    slug: 'call-center-qa-compliance',
    title: 'CC Intermediate · QA y compliance',
    description: 'Habla con calidad auditada y cumplimiento de politicas.',
    level: LessonLevel.ADVANCED,
    category: LessonCategory.CALL_CENTER,
    order: 11,
    isPremium: true,
    syllabus: [
      'Criterios de calidad de llamada',
      'Frases obligatorias',
      'Avisos legales basicos',
      'Evitar promesas indebidas',
      'Privacidad y datos sensibles',
      'Estructura de llamada auditada',
      'Control de tiempos',
      'Documentacion post-llamada',
      'Errores criticos de compliance',
      'Autochequeo de QA',
      'Revision de caso grabado',
      'Plan de mejora mensual',
    ],
  },
  {
    slug: 'call-center-closing-followup',
    title: 'CC Intermediate · Cierre y follow-up',
    description: 'Cierra llamadas con acuerdos claros y siguiente paso definido.',
    level: LessonLevel.INTERMEDIATE,
    category: LessonCategory.CALL_CENTER,
    order: 12,
    isPremium: true,
    syllabus: [
      'Resumen final de solucion',
      'Confirmar entendimiento del cliente',
      'Proximo paso y responsable',
      'Canal de seguimiento',
      'Tiempo de respuesta esperado',
      'Frases de despedida profesional',
      'Invitar a feedback',
      'Evitar cierres abruptos',
      'Reducir recontacto',
      'Registro final del caso',
      'Role-play de cierre completo',
      'Checklist de salida impecable',
    ],
  },
];

async function main() {
  const premiumEmail = process.env.SEED_PREMIUM_EMAIL || 'premium@hablaspeak.com';
  const premiumPassword = process.env.SEED_PREMIUM_PASSWORD || 'Premium123!';
  const freeEmail = process.env.SEED_FREE_EMAIL || 'demo@hablaspeak.com';
  const freePassword = process.env.SEED_FREE_PASSWORD || 'Demo123!';

  await prisma.user.upsert({
    where: { email: premiumEmail },
    update: {
      name: 'Premium Tester',
      hashedPassword: hashPassword(premiumPassword),
      plan: Plan.PREMIUM,
    },
    create: {
      email: premiumEmail,
      name: 'Premium Tester',
      hashedPassword: hashPassword(premiumPassword),
      plan: Plan.PREMIUM,
      streakCurrent: 3,
    },
  });

  await prisma.user.upsert({
    where: { email: freeEmail },
    update: {
      name: 'Free Tester',
      hashedPassword: hashPassword(freePassword),
      plan: Plan.FREE,
    },
    create: {
      email: freeEmail,
      name: 'Free Tester',
      hashedPassword: hashPassword(freePassword),
      plan: Plan.FREE,
      streakCurrent: 1,
    },
  });

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { slug: lesson.slug },
      update: lesson,
      create: lesson,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async error => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
